create table if not exists public.cloud_saves (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  system text not null,
  game_id text not null,
  save_kind text not null,
  rom_name text not null default '',
  payload_json jsonb not null,
  updated_at timestamptz not null default now()
);

create unique index if not exists cloud_saves_user_game_kind_idx
  on public.cloud_saves (user_id, system, game_id, save_kind);

alter table public.cloud_saves enable row level security;

create policy "cloud_saves_select_own"
  on public.cloud_saves
  for select
  using (auth.uid() = user_id);

create policy "cloud_saves_insert_own"
  on public.cloud_saves
  for insert
  with check (auth.uid() = user_id);

create policy "cloud_saves_update_own"
  on public.cloud_saves
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "cloud_saves_delete_own"
  on public.cloud_saves
  for delete
  using (auth.uid() = user_id);
